### PR TITLE
Please consider dropping Google Analytics

### PR DESCRIPTION
**Pull request by alexwykoff**
Quite a few users I know are not big fans of the big G. Would you consider dropping the tracking?

### CODE REVIEW

**Comment by bradleyrichter** [comment]
or at least provide a toggle or branch to a tracking-free version...

**Comment by diracdeltas** [comment]
++ would be great to have this as a widget option.

**Comment by jdc20181** [comment]
They need it, as much as we do not like Google (well some of us), we need the data to prove how many rely on the internet, while there is other ways to get this data, google is the most secure. Hopefully they will step in and support the cause also.

**Comment by holmesworcester** [comment]
they are participating in the day of action, according to press reports.

we will typically use a piwik instance but there wasn’t time. if someone can create a PR for an option to remove it we would accept that, I believe.

some people are self hosting the widget, and would be free to remove it in that case.

**Pull request closed without merging**
