### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by thatrobotdev**
I created a version of this script, that could be added to people's CodePens to let them rally as well. With this change, it adds this script under the section Plugins.

### CODE REVIEW

**Comment by mikemorris** [comment]
Ack, is there a nicer way to do this than using `document.write` for every line?

**Comment by jamesjpk123** [comment]
Maybe @mikemorris, but it was the fastest way I could deploy it. With the day coming tomorrow, I tried to create it as fast as possible.

**Comment by Dorian** [comment]
Looks like a blank page to me

**Comment by jamesjpk123** [comment]
Guess it doesn't work. Hope everyone had a good net neutrality day though!

**Pull request closed without merging**
