### PR TITLE
Don't show widget if useragent matches bot/crawler

### PR DESCRIPTION
**Pull request by Sgtpanda**
Uses regex used by [Agent_Orange](https://github.com/kevinelliott/agent_orange) to detect bots and stop any potential SEO degradation 

mitigates #65 

(Side note, this is my first pull request/commit to an external project so sorry if I've messed something up)

### CODE REVIEW

**Comment by mikemorris** [comment]
@decoy31 How does this look to you?

@Sgtpanda I'm hesitant to merge right now without trying to sample UAs from our current submissions, but the general approach here looks promising!

**Review by decoy31 — APPROVED** [review]
Looks good to me.

**Comment by Dorian** [comment]
Needs lot of testing

**Comment by mikemorris** [comment]
Closing this as `wontfix` due to lack of capacity for thoroughly testing this change, see https://github.com/fightforthefuture/battleforthenet-widget/issues/65#issuecomment-337065821

**Pull request closed without merging**
